# Generated by Django 5.2.5 on 2026-04-29 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=15, verbose_name='Alıcı Numarası')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('sent', 'Gönderildi'), ('failed', 'Başarısız'), ('pending', 'Bekliyor')], default='pending', max_length=10, verbose_name='Durum')),
                ('twilio_sid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twilio SID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logları',
                'ordering': ['-created_at'],
            },
        ),
    ]
