# Generated by Django 5.2.5 on 2025-12-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_remove_panel_category_panel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='categories',
            field=models.ManyToManyField(blank=True, to='panel.category'),
        ),
    ]
