# Generated by Django 5.2.5 on 2026-07-16 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Panel', 'verbose_name_plural': 'Paneller'},
        ),
        migrations.AddField(
            model_name='panel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='panel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
