# Generated by Django 5.2.5 on 2026-04-29 02:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hesap Adı')),
                ('type', models.CharField(choices=[('bank', 'Banka Hesabı'), ('cash', 'Nakit'), ('credit_card', 'Kredi Kartı'), ('other', 'Diğer')], max_length=20, verbose_name='Hesap Türü')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bakiye')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Cari Hesap',
                'verbose_name_plural': 'Cari Hesaplar',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('type', models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider')], max_length=10, verbose_name='Tür')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Renk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider'), ('transfer', 'Transfer')], max_length=10, verbose_name='İşlem Türü')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('recipient', models.CharField(blank=True, max_length=100, verbose_name='Alıcı')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Hesap')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'expense'}, on_delete=django.db.models.deletion.CASCADE, to='accounting.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider'), ('transfer', 'Transfer')], max_length=10, verbose_name='İşlem Türü')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Kaynak')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Hesap')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'income'}, on_delete=django.db.models.deletion.CASCADE, to='accounting.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Gelir',
                'verbose_name_plural': 'Gelirler',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='accounting.account', verbose_name='Gönderen Hesap')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='accounting.account', verbose_name='Alan Hesap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transferler',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
