# Generated by Django 5.2.5 on 2026-07-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='recipient',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ödeme Yöntemi'),
        ),
    ]
